[package]
name = "http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1.1.0", features = ["full"] }
hyper-util = { version = "0.1.2", features = ["full", "client"] }
tokio = { version = "1.35.1", features = ["full"] }
http-body-util = "0.1.0"
bytes = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
