name: Publish

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update to latest Rust
        run: rustup update

      - name: Publish using cargo
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_TERM_COLOR: always
          RUSTFLAGS: "-D warnings"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cargo-proxy
          path: target/*/*.crate
