name: Publish

on:
  workflow_call:
    inputs:
      dry:
        description: 'Do not do actual publish'
        required: true
        type: boolean


env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CARGO_INCREMENTAL: 0

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update to latest Rust
        run: rustup update

      - name: Run publish dry-run first run
        run: |
          cargo publish --locked --dry-run
          mkdir -p ${{ runner.temp }}
          sha256sum target/package/*.crate > ${{ runner.temp }}/SHA256SUMS.txt
          cat ${{ runner.temp }}/SHA256SUMS.txt
          rm -r target/

      - name: Run publish dry-run second run
        run: |
          cargo publish --locked --dry-run
          cat ${{ runner.temp }}/SHA256SUMS.txt
          sha256sum -c ${{ runner.temp }}/SHA256SUMS.txt
          rm -r target/

      - name: Publish using cargo
        if: inputs.dry == false
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish using cargo fake
        if: inputs.dry == true
        run: cargo publish --locked --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Verify checksum after publish
        run: |
          cat ${{ runner.temp }}/SHA256SUMS.txt
          sha256sum -c ${{ runner.temp }}/SHA256SUMS.txt

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: target/package/ollama-proxy-*.crate

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cargo-proxy
          path: target/package/ollama-proxy-*.crate
