name: Publish

on:
  workflow_dispatch:  # Allow manual triggering

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CARGO_INCREMENTAL: 0

jobs:
  publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update to latest Rust
        run: rustup update

      - name: Run publish dry-run first run
        run: |
          cargo publish --locked --dry-run
          mkdir -p .github/temp
          sha256sum target/package/*.crate > .github/temp/SHA256SUMS.txt
          cat .github/temp/SHA256SUMS.txt
          rm -r target/

      - name: Run publish dry-run second run
        run: |
          cargo publish --locked --dry-run
          cat .github/temp/SHA256SUMS.txt
          sha256sum -c .github/temp/SHA256SUMS.txt
          rm -r target/

      - name: Publish using cargo
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_TERM_COLOR: always
          RUSTFLAGS: "-D warnings"

      - name: Verify checksum after publish
        run: |
          cat .github/temp/SHA256SUMS.txt
          sha256sum -c .github/temp/SHA256SUMS.txt

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cargo-proxy
          path: target/*/*.crate
