name: Publish

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update to latest Rust
        run: rustup update

      - name: Run publish dry-run first run
        run: |
          cargo publish --dry-run
          sha256sum target/package/*.crate > SHA256SUMS.txt
          cat SHA256SUMS.txt
          rm -r target/

      - name: Run publish dry-run second run
        run: |
          cargo publish --dry-run
          cat SHA256SUMS.txt
          sha256sum -c SHA256SUMS.txt
          rm -r target/

      - name: Publish using cargo
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          CARGO_TERM_COLOR: always
          RUSTFLAGS: "-D warnings"

      - name: Verify checksum after publish
        run: |
          cat SHA256SUMS.txt
          sha256sum -c SHA256SUMS.txt

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cargo-proxy
          path: target/*/*.crate
